server:
  port: 9000
spring:
  application:
    name: GatewayDemo
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启当前项目服务注册与发现功能
          lower-case-service-id: true # 把服务名转换为小写，Eureka中默认都是大写
      routes:
        #list list类型且为范型，需要加‘-’
        - id: one #id
          uri: lb://project-demo # lb:loadBalance EUREKA-CLIENT 默认的负载均衡策略是轮询
          predicates:
            - Path=/demo/** # 路径规则
            #不允许Query=name,age*  这个代表name的值必须是age*开头的，这里可以用正则匹配
            - Query=name #必须包含请求参数名称，否则不进行路由
            - name: Query
              args:
                param: age
                regexp: \d{1,3} #年龄必须是1到3位
            - Header=Connection,keep-alive #请求头必须有这个参数，并且参数值是keep-alive
            - Method=GET,POST #支持的方法类型
            #- RemoteAddr=192.168.31.***
            #- RemoteAddr=127.0.0.1 #允许访问的远程地址，不能写127这个，要写局域网ip
            #- Host=192.168.31.xxx:9000  同样不能用127
            #- Cookie=abc,.{3} #cookie取值是3位
            - Before=2028-01-30T15:00:00Z #在某个时间之前执行
            - After=2024-01-01T00:00:00Z #在某个时间之后执行
            - Between=2021-01-01T00:00:00Z,2028-01-30T15:00:00Z #在某个时间端内执行
         # filters: StripPrefix=1 #转发后忽略第一层
